version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: stanbychkov/uniqlo_bot:latest
    restart: always
    command: python uniqlo_bot.py
    env_file:
      - ./.env